name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Build_Push_Image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./src
          tags: ghcr.io/azure/gitops-connector:latest

